#!/bin/sh
# Compile only caller-owned ROM text/font pages; generated bytes stay ignored.
set -eu
rom=${1:-local/Tenchi Souzou (Japan).sfc}
probe=local/house-dialogue-qualification/probe
mkdir -p "$probe/src"
cp tools/house-dialogue-qualification/export.rs "$probe/src/main.rs"
cat >"$probe/Cargo.toml" <<'TOML'
[package]
name = "house-dialogue-export"
version = "0.0.0"
edition = "2021"
[workspace]
[dependencies]
rom = { path = "../../../crates/rom" }
assets = { path = "../../../crates/assets" }
serde_json = "1"
TOML
cargo build --release --manifest-path "$probe/Cargo.toml"
root=$(mktemp -d local/house-dialogue-qualification/export-XXXXXX)
"${CARGO_TARGET_DIR:-$probe/target}/release/house-dialogue-export" "$rom" "$root/pages"
for flags in '-B' '-O -B'; do
    python3 $flags tools/house-dialogue-qualification/test_check.py "$rom" "$root/pages"
    python3 $flags tools/house-dialogue-qualification/check.py "$rom" "$root/pages"
done
printf '%s\n' "$root"
