#!/usr/bin/env python3
"""Writes the Rust table of European addresses from jp-to-eu.tsv.

Usage: emit.py jp-to-eu.tsv crates/assets/src/layout/europe.rs

Keeps the high- and medium-confidence rows; the low ones (text bank $92,
estimates) are set by hand where the decoders need them.
"""
import sys


def address(text):
    bank, offset = text.split(':')
    return int(bank, 16) << 16 | int(offset, 16)


def main(source, target):
    rows = []
    with open(source) as tsv:
        next(tsv)
        for line in tsv:
            jp, eu, kind, method, confidence = line.rstrip('\n').split('\t')[:5]
            if confidence in ('high', 'medium'):
                rows.append((address(jp), address(eu), kind, method, confidence))
    rows.sort()
    with open(target, 'w') as out:
        out.write('//! Generated by `tools/eu-map/emit.py` from `tools/eu-map/jp-to-eu.tsv`;\n')
        out.write('//! do not edit. Each pair is a Japanese address and its European one,\n')
        out.write('//! sorted, with the kind, method and confidence the map found.\n\n')
        out.write('/// (Japanese, European) addresses, sorted by the Japanese one.\n')
        out.write('pub(super) const EUROPE: &[(u32, u32)] = &[\n')
        for jp, eu, kind, method, confidence in rows:
            out.write(f'    (0x{jp >> 16:02X}_{jp & 0xFFFF:04X}, 0x{eu >> 16:02X}_{eu & 0xFFFF:04X}), // {kind}, {method}, {confidence}\n')
        out.write('];\n')


if __name__ == '__main__':
    main(*sys.argv[1:3])
